spring:
  application:
    name: api-gateway
  main:
    web-application-type: REACTIVE
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: etudiant_ms
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
        - id: professeur_ms
          uri: http://localhost:8083
          predicates:
            - Path=/api/**
        - id: classes_ms
          uri: http://localhost:8084
          predicates:
            - Path=/graphiql/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080
